# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate dottxt-ai
#
name: outlines-core-dev
channels:
  - conda-forge
  - huggingface
dependencies:
  - python==3.10.0
  - pydantic
  - pytest
  - pre-commit
  - jsonschema
  - pip
  - pip:
    - -e ".[test]"
